import{useEffect,useState}from'react';
import{ArrowDown,ArrowUpRight,Download,Mail,Menu,X}from'lucide-react';

const projects=[
 {number:'01',title:'Database Engine',description:'Disk-backed key-value storage engine with B+ tree indexing, linked leaf range scans, overflow pages, and runtime cache metrics.',tags:['C++','STL','React','TypeScript'],href:'https://github.com/colekenn/database-engine',visual:'database',image:'/database-project.png'},
 {number:'02',title:'Async Job Queue',description:'Dockerized background job service with a FastAPI entrypoint, Redis queue, PostgreSQL persistence, retries, and rate-limited APIs.',tags:['Python','FastAPI','Redis','PostgreSQL','Docker'],href:'https://github.com/colekenn/async-job-queue',visual:'queue'},
 {number:'03',title:'Algorithm Visualizer',description:'Interactive sorting algorithm visualizer with animated D3 bar transitions and adjustable playback controls.',tags:['React','TypeScript','D3','Vite'],href:'https://github.com/colekenn/algorithm-visualizer',demo:'https://algorithm-visualizer-nu-seven.vercel.app/',visual:'algorithm',image:'/algorithm-project.png'}
];
const experience=[
 {role:'Software Engineer Intern',company:'Evolv Technology',period:'Jun. 2026 — Present',logo:'/evolv-logo.png',summary:'Building an integrated React and TypeScript alignment workflow for live X-ray detector hardware, connected to embedded C++ services through gRPC.'},
 {role:'Software Engineer Intern',company:'Knead',period:'Oct. 2025 — May 2026',logo:'/knead-logo.jpeg',summary:'Built trading-strategy generation, simulation, authentication, and asynchronous backtesting systems across Python and AWS-backed services.'},
 {role:'Instructional Assistant',company:'University of South Carolina',period:'Aug. 2025 — Present',logo:'/usc-experience-logo.jpg',summary:'Lead weekly peer instruction in advanced C++, data structures, algorithmic analysis, memory management, and debugging.'}
];
const skills=[['Languages','Python · TypeScript · JavaScript · C++ · Java · SQL · HTML · CSS'],['Frameworks','React · Electron · FastAPI · Flask · Tailwind CSS'],['Technologies','gRPC · Protobuf · PostgreSQL · Supabase · Redis · Docker · Git · Linux · AWS Cognito']];

export default function App(){
 const[menuOpen,setMenuOpen]=useState(false);const[scrolled,setScrolled]=useState(false);
 useEffect(()=>{const update=()=>setScrolled(window.scrollY>24);update();window.addEventListener('scroll',update);return()=>window.removeEventListener('scroll',update)},[]);
 useEffect(()=>{
  const targets=[...document.querySelectorAll<HTMLElement>('main section:not(.hero) .section-label, main section:not(.hero) h2, .school-strip, .about-lead p, .stats > div, .honors, .coursework, .project-card, .text-link, .experience-list article, .skill-row, .contact-copy, .contact-links > a')];
  targets.forEach((element,index)=>{element.classList.add('scroll-reveal');element.style.setProperty('--reveal-order',String(index%4))});
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -48px'});
  targets.forEach(element=>observer.observe(element));
  return()=>observer.disconnect();
 },[]);
 return <div className="site-shell">
  <header className={scrolled?'nav scrolled':'nav'}><a className="logo" href="#top" aria-label="Home">CK<span>.</span></a><nav className={menuOpen?'nav-links open':'nav-links'} aria-label="Main navigation">{['About','Experience','Projects','Skills'].map(x=><a key={x} href={`#${x.toLowerCase()}`} onClick={()=>setMenuOpen(false)}>{x}</a>)}<a className="nav-contact" href="mailto:colekennedy56@gmail.com">Let’s talk <ArrowUpRight size={15}/></a></nav><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation" aria-expanded={menuOpen}>{menuOpen?<X/>:<Menu/>}</button></header>
  <main id="top">
   <section className="hero section"><div className="hero-mark" aria-hidden="true"><span>C</span><span>K</span></div><div className="hero-layout"><div className="hero-intro"><p className="intro-line intro-one">Hi, I’m</p><h1 className="intro-line intro-two hero-title" aria-label="Cole Kennedy"><span className="name-line"><span>Cole</span></span><span className="name-line"><span>Kennedy<span className="period">.</span></span></span></h1><p className="hero-role intro-line intro-three">Aspiring software engineer<span className="cursor" aria-hidden="true"/></p><p className="hero-description intro-line intro-four">Computer Science at the University of South Carolina. Interested in full-stack and systems engineering.</p><div className="hero-actions intro-line intro-five"><a className="button primary" href="#projects">View projects <ArrowDown size={17}/></a><a className="button secondary" href="/resume.pdf" target="_blank" rel="noreferrer">Résumé <Download size={16}/></a></div></div><figure className="hero-photo intro-line intro-three" aria-label="Portrait of Cole Kennedy"><div className="photo-frame"><img src="/cole-portrait.jpg" alt="Cole Kennedy"/></div></figure></div><div className="hero-meta intro-line intro-five"><span>Graduating December 2027</span><span>3.93 GPA</span></div></section>
   <aside className="school-strip" aria-label="Education"><a href="https://sc.edu" target="_blank" rel="noreferrer"><img src="/usc-logo.svg" alt="University of South Carolina logo"/></a><div className="school-detail"><span>Degree</span><strong>B.S. Computer Science</strong></div><div className="school-detail"><span>Graduation</span><strong>December 2027</strong></div><div className="school-detail"><span>GPA</span><strong>3.93 / 4.00</strong></div></aside>
   <section id="about" className="section split-section"><Label n="01" text="About"/><div className="about-content"><div className="about-lead"><div><h2>CS student building full-stack products and systems software.</h2><p>I’m studying at the University of South Carolina with experience across product engineering, hardware-connected workflows, and peer instruction.</p></div></div><div className="stats"><div><strong>3.93</strong><span>GPA</span></div><div><strong>3×</strong><span>President’s Honor List</span></div><div><strong>2027</strong><span>Expected graduation</span></div></div><div className="honors">Academic Scholar — Distinction Award <span>·</span> Capstone Scholar <span></span></div><div className="coursework"><span>Coursework</span>Data Structures &amp; Algorithms · Operating Systems · Software Engineering · Computer Architecture · Advanced C++ · UNIX/Linux</div></div></section>
   <section id="experience" className="section split-section experience-section"><Label n="02" text="Experience"/><div className="experience-list">{experience.map((x,i)=><article key={x.company+x.role}><span className="experience-index">0{i+1}</span><img className="experience-logo" src={x.logo} alt={`${x.company} logo`}/><div className="experience-main"><div><h3>{x.role}</h3><p>{x.company}</p></div><p className="experience-summary">{x.summary}</p></div><span className="experience-type">{x.period}</span></article>)}</div></section>
   <section id="projects" className="section projects-section"><div className="section-heading"><Label n="03" text="Projects"/><h2>Selected technical work.</h2></div><div className="project-grid">{projects.map(p=><article className="project-card" key={p.title}><div className="project-top"><span>{p.number}</span><a href={p.demo??p.href} target="_blank" rel="noreferrer" aria-label={`Open ${p.title}`}><ArrowUpRight size={21}/></a></div><ProjectVisual type={p.visual} image={p.image}/><div className="project-body"><h3>{p.title}</h3><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-links">{p.demo&&<a className="project-link" href={p.demo} target="_blank" rel="noreferrer">Live site <ArrowUpRight size={15}/></a>}<a className="project-link" href={p.href} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a></div></div></article>)}</div><a className="text-link" href="https://github.com/colekenn" target="_blank" rel="noreferrer">More on GitHub <ArrowUpRight size={16}/></a></section>
   <section id="skills" className="section split-section skills-section"><Label n="04" text="Skills"/><div className="skills-content"><h2>What I work with.</h2>{skills.map(([a,b])=><div className="skill-row" key={a}><h3>{a}</h3><p>{b}</p></div>)}</div></section>
   <section id="contact" className="section contact-section"><div className="eyebrow">Links</div><h2>Connect <em>with me.</em></h2><p className="contact-copy">Email me directly, or find my work and background through GitHub and LinkedIn.</p><div className="contact-links"><a href="mailto:colekennedy56@gmail.com"><Mail size={20}/><span><small>Email</small>colekennedy56@gmail.com</span><ArrowUpRight size={18}/></a><a href="https://github.com/colekenn" target="_blank" rel="noreferrer"><GitHubIcon/><span><small>GitHub</small>github.com/colekenn</span><ArrowUpRight size={18}/></a><a href="https://linkedin.com/in/coleken" target="_blank" rel="noreferrer"><LinkedInIcon/><span><small>LinkedIn</small>linkedin.com/in/coleken</span><ArrowUpRight size={18}/></a></div></section>
  </main>
  <footer><span>© {new Date().getFullYear()} Cole Kennedy</span><div className="socials"><a href="https://github.com/colekenn" target="_blank" rel="noreferrer" aria-label="GitHub"><GitHubIcon/></a><a href="https://linkedin.com/in/coleken" target="_blank" rel="noreferrer" aria-label="LinkedIn"><LinkedInIcon/></a><a href="mailto:colekennedy56@gmail.com" aria-label="Email"><Mail size={18}/></a></div><a href="#top">Back to top <ArrowDown className="up-arrow" size={16}/></a></footer>
 </div>
}
function ProjectVisual({type,image}:{type:string,image?:string}){
 if(image)return <div className={`project-visual screenshot-visual ${type}-screenshot`}><img src={image} alt={`${type} project screenshot`}/></div>;
 return <div className="project-visual queue-visual" aria-label="Async job queue architecture preview"><div className="queue-window"><div className="queue-bar"><span/><span/><span/></div><div className="queue-flow compact"><div><strong>FastAPI</strong><small>POST /jobs</small></div><div><strong>Redis</strong><small>job_queue</small></div><div><strong>Worker</strong><small>retry + backoff</small></div><div><strong>Postgres</strong><small>job state</small></div></div><div className="queue-terminal"><span>[worker] processing job 42</span><span>{'{'} status: "succeeded", attempts: 1 {'}'}</span></div></div></div>
}
function Label({n,text}:{n:string,text:string}){return <div className="section-label"><span>{n}</span>{text}</div>}
function GitHubIcon(){return <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><path d="M12 .7A11.5 11.5 0 0 0 8.36 23.1c.58.1.79-.25.79-.56v-2.2c-3.22.7-3.9-1.37-3.9-1.37-.53-1.34-1.29-1.7-1.29-1.7-1.05-.72.08-.71.08-.71 1.17.08 1.78 1.2 1.78 1.2 1.04 1.77 2.72 1.26 3.38.96.1-.75.4-1.26.74-1.55-2.57-.3-5.27-1.29-5.27-5.69 0-1.26.45-2.28 1.19-3.09-.12-.29-.52-1.46.11-3.05 0 0 .97-.31 3.16 1.18a10.9 10.9 0 0 1 5.75 0c2.2-1.49 3.16-1.18 3.16-1.18.63 1.59.23 2.76.11 3.05.74.81 1.19 1.83 1.19 3.09 0 4.42-2.71 5.39-5.29 5.68.42.36.79 1.06.79 2.14v3.18c0 .31.21.67.8.56A11.5 11.5 0 0 0 12 .7Z"/></svg>}
function LinkedInIcon(){return <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" aria-hidden="true"><path d="M20.45 20.45h-3.56v-5.57c0-1.33-.03-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.34V8.98h3.42v1.57h.05c.47-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.29ZM5.32 7.41a2.07 2.07 0 1 1 0-4.13 2.07 2.07 0 0 1 0 4.13Zm1.78 13.04H3.54V8.98H7.1v11.47Z"/></svg>}
